// frontend-react/src/components/ShipSelect.tsx
import { useEffect, useState } from 'react'
import { Select } from 'antd'
import { getShips } from '../api/ships'

interface ShipSelectProps {
  value?: number
  onChange?: (value: number) => void
  placeholder?: string
  disabled?: boolean
}

export default function ShipSelect({ value, onChange, placeholder = '请选择船舶', disabled }: ShipSelectProps) {
  const [options, setOptions] = useState<{ label: string; value: number }[]>([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    getShips({ pageSize: 100 })
      .then((res) => {
        setOptions(res.records.map((s) => ({ label: s.shipName, value: s.id })))
      })
      .finally(() => setLoading(false))
  }, [])

  return (
    <Select
      value={value}
      onChange={onChange}
      options={options}
      placeholder={placeholder}
      loading={loading}
      disabled={disabled}
      allowClear
      showSearch
      optionFilterProp="label"
      style={{ width: '100%' }}
    />
  )
}

// frontend/src/components/ShipSelect.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getShips, type Ship } from '../api/ships'

const model = defineModel<number | null | undefined>()

const props = withDefaults(
  defineProps<{
    placeholder?: string
    enabledOnly?: boolean
  }>(),
  {
    placeholder: '请选择船舶',
    enabledOnly: false,
  },
)

const loading = ref(false)
const ships = ref<Ship[]>([])

const options = computed(() => {
  if (!props.enabledOnly) {
    return ships.value
  }
  return ships.value.filter((ship) => ship.status !== 'DISABLED')
})

async function loadShips() {
  loading.value = true
  try {
    const result = await getShips({
      page: 1,
      pageSize: 100,
      status: '',
    })
    ships.value = result.records
  } finally {
    loading.value = false
  }
}

onMounted(loadShips)
</script>

<template>
  <el-select v-model="model" clearable filterable :loading="loading" :placeholder="placeholder">
    <el-option
      v-for="ship in options"
      :key="ship.id"
      :label="`${ship.shipName}（${ship.shipNo}）`"
      :value="ship.id"
    />
  </el-select>
</template>
