// frontend/src/components/TransportOrderSelect.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getTransportOrders, type TransportOrder } from '../api/transportOrders'

const model = defineModel<number | null | undefined>()

const props = withDefaults(
  defineProps<{
    placeholder?: string
    withoutSettlementOnly?: boolean
  }>(),
  {
    placeholder: '请选择运输任务',
    withoutSettlementOnly: false,
  },
)

const loading = ref(false)
const orders = ref<TransportOrder[]>([])

const options = computed(() => {
  if (!props.withoutSettlementOnly) {
    return orders.value
  }
  return orders.value.filter((order) => !order.settlementId)
})

async function loadOrders() {
  loading.value = true
  try {
    const result = await getTransportOrders({
      page: 1,
      pageSize: 100,
      status: '',
    })
    orders.value = result.records
  } finally {
    loading.value = false
  }
}

onMounted(loadOrders)
</script>

<template>
  <el-select v-model="model" clearable filterable :loading="loading" :placeholder="placeholder">
    <el-option
      v-for="order in options"
      :key="order.id"
      :label="`${order.orderNo}（${order.customerName}）`"
      :value="order.id"
    />
  </el-select>
</template>

// frontend-react/src/components/TransportOrderSelect.tsx
import { useEffect, useState } from 'react'
import { Select } from 'antd'
import { getTransportOrders } from '../api/transportOrders'

interface TransportOrderSelectProps {
  value?: number
  onChange?: (value: number) => void
  placeholder?: string
  disabled?: boolean
}

export default function TransportOrderSelect({ value, onChange, placeholder = '请选择运输任务', disabled }: TransportOrderSelectProps) {
  const [options, setOptions] = useState<{ label: string; value: number }[]>([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    getTransportOrders({ pageSize: 100 })
      .then((res) => {
        setOptions(res.records.map((t) => ({ label: `${t.orderNo} - ${t.cargoName}`, value: t.id })))
      })
      .finally(() => setLoading(false))
  }, [])

  return (
    <Select
      value={value}
      onChange={onChange}
      options={options}
      placeholder={placeholder}
      loading={loading}
      disabled={disabled}
      allowClear
      showSearch
      optionFilterProp="label"
      style={{ width: '100%' }}
    />
  )
}
